---
- hosts: localhost
  become: true

  vars:
    username: "vagrant"
    home: "/home/{{ username }}"
    document_root: "/{{ username }}"

  pre_tasks:
    - name: Install stuff from Aptitude
      apt: 
        name="{{ item }}"
        state=present
        update_cache=yes 
        cache_valid_time=86400
      with_items:
       - git
       - tig
       - vim
       - gcc
       - gdb
       - cgdb
       - bash-completion # Not included in the docker image
       - make
       - tree
       - htop
       - man-db
       - libssl-dev # used by python2 for SSL checking
       - libffi-dev

  roles:
    - zsh
    - vim
